name: data_repository
description: A generic repository that acts as an abstraction layer over an DataClient.
repository: https://github.com/flutter-news-app-full-source-code/data-repository
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  core:
    git:
      url: https://github.com/flutter-news-app-full-source-code/core.git
      ref: 828b984517edec069266579c624c7af9fbe0e2ac
  data_client:
    git:
      url: https://github.com/flutter-news-app-full-source-code/data-client.git
      ref: 960a00882045ee252274d9d57bfca606c1fe5d64

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.24.0
  very_good_analysis: ^9.0.0
